name: prasso_app
description: or To Get It Done
publish_to: 'none' 

version: 1.0.0+20

environment:
  sdk: ">=2.8.4 <3.0.0"

dependencies:

  amazon_s3_cognito: ^0.6.0
  cached_network_image: ^2.2.0+1
  cloud_firestore: ^0.14.1+3
  cloud_functions: ^0.7.2
  cupertino_icons: ^0.1.2
  dynamic_widget: ^3.0.1
  #firebase_analytics: any
  firebase_auth: ^0.18.1+2
  firebase_core: ^0.5.0+1
  #firebase_crashlytics: ^0.4.0+1
  firebase_messaging: ^7.0.3
  firebase_storage: ^5.0.1
  flutter:
    sdk: flutter  
  flutter_cached_pdfview: any
  flutter_config: ^1.0.7
  flutter_hooks: any
  flutter_image_compress: any
  # https://stackoverflow.com/questions/62476108/how-to-load-and-present-a-pdf-file-from-the-web-in-flutter
  flutter_native_timezone: ^1.0.10
  flutter_pdfview: ^1.0.1
  flutter_svg: ^0.19.1
  hooks_riverpod: ^0.14.0+3
  http: ^0.12.2
  icons_helper: ^1.0.4
  image_picker: ^0.6.7+15
  intl: ^0.16.1
  logger: ^0.9.2
  path_provider: any
  pedantic: any
  permission_handler: 4.4.0  
  # For asking permission to load the pdf
  rxdart: ^0.24.1
  shared_preferences: ^0.5.12+2
  state_notifier: any
  syncfusion_flutter_calendar: ^18.4.46
  toggle_switch: ^1.2.0
  video_player: ^2.1.14
  webview_flutter: ^0.3.14+1

# this is to fix an exception in Android on launch
dependency_overrides:
  extended_image: any

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  import_sorter: ^4.4.1
  mockito: ^4.1.1
  random_string: ^2.0.0
  test: any

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
   - media/prasso_logo_horizontal.png
   - media/prasso_logo.png
   - media/Mobilewireframe-rafiki.svg
   - media/Operatingsystemupgrade-pana.svg
   - media/Phonemaintenance-rafiki.svg
   - media/Optamize.mov
   - media/Screen1-Movingforward-pana.svg
   - media/Screen2-Teaching-cuate.svg
   - media/Screen3-Onlinecalendar-bro.svg
   - media/Calendar-cuate.svg
  #  - images/a_dot_ham.jpeg
 

